const PM = {
  watershed: { label: "Watershed & land use", ac: "#639922", bg: "#EAF3DE", tip: "Controls forest cover, agriculture, and runoff into rivers feeding the Salish Sea", p: {
    forestCover: { l: "Forest cover", u: "%", mn: 0, mx: 100, s: 1 },
    imperviousSurface: { l: "Impervious surface", u: "%", mn: 0, mx: 80, s: 1 },
    precipitation: { l: "Precipitation", u: "mm/mo", mn: 20, mx: 300, s: 5 },
    agriculturalArea: { l: "Agricultural area", u: "%", mn: 0, mx: 60, s: 1 },
    riparianBufferWidth: { l: "Riparian buffer", u: "m", mn: 0, mx: 100, s: 5 },
    nutrientMgmt: { l: "Ag nutrient mgmt", u: "%", mn: 0, mx: 100, s: 5 },
    damRemovalPolicy: { l: "Dam removal policy", u: "", mn: 0, mx: 3, s: 1, f: function(v) { return ["No change","Passage upgrade","Partial removal","Full removal"][v] || "No change"; } },
    waterConservation: { l: "Water conservation", u: "%", mn: 0, mx: 100, s: 5, sourceHint: "WA Ecology instream flow rules. Reduces agricultural/municipal withdrawals." },
    instreamFlowProtection: { l: "Instream flow protection", u: "%", mn: 0, mx: 100, s: 5, sourceHint: "Winters doctrine, Nooksack adjudication. Protects minimum flows for salmon." },
  }},
  marine: { label: "Marine & oceanographic", ac: "#378ADD", bg: "#E6F1FB", tip: "Ocean conditions: temperature, stratification, tidal exchange across 6 sub-basins", p: {
    tidalExchangeRate: { l: "Tidal exchange", u: "%", mn: 10, mx: 100, s: 5 },
    baselineTemperature: { l: "Baseline SST", u: "°C", mn: 6, mx: 18, s: 0.5 },
    oceanCurrentStrength: { l: "Current strength", u: "%", mn: 10, mx: 100, s: 5 },
    stratificationStrength: { l: "Stratification", u: "%", mn: 10, mx: 90, s: 5 },
    sspPathway: { l: "Climate pathway", u: "", mn: 0, mx: 2, s: 1, f: function(v) { return ["SSP1-2.6","SSP2-4.5","SSP5-8.5"][v] || "SSP2-4.5"; } },
    tidalEnergyExtraction: { l: "Tidal energy", u: "MW", mn: 0, mx: 100, s: 5 },
    slrScenario: { l: "SLR scenario", u: "", mn: 0, mx: 4, s: 1, f: function(v) { return ["Historical only", "IPCC likely", "Accelerated", "Thwaites collapse", "WAIS+Greenland"][v] || "?"; } },
    greenlandScenario: { l: "Greenland ice loss", u: "", mn: 0, mx: 3, s: 1, f: function(v) { return ["Stable", "Moderate", "Accelerated", "Destabilized"][v] || "?"; } },
    ensoAmplification: { l: "ENSO amplification", u: "\u00D7", mn: 0.5, mx: 2.0, s: 0.1 },
  }},
  port: { label: "Port & economy", ac: "#BA7517", bg: "#FAEEDA", tip: "Shipping traffic, vessel noise, dredging, tourism, military presence, and economic output", p: {
    containerThroughput: { l: "Container throughput", u: "TEU", mn: 500, mx: 8000, s: 100 },
    avgVesselSize: { l: "Avg vessel size", u: "kDWT", mn: 10, mx: 120, s: 5 },
    dredgingIntensity: { l: "Dredging", u: "%", mn: 0, mx: 100, s: 5 },
    shorepower: { l: "Shore power", u: "%", mn: 0, mx: 100, s: 5 },
    tourismLevel: { l: "Tourism", u: "%", mn: 0, mx: 100, s: 5 },
    militaryPresence: { l: "Military presence", u: "%", mn: 0, mx: 100, s: 5 },
    autonomousVessels: { l: "Autonomous vessels", u: "%", mn: 0, mx: 50, s: 1 },
    vesselSpeedZone: { l: "Speed reduction zone", u: "%", mn: 0, mx: 100, s: 5 },
    altFuelFraction: { l: "Alt fuel (LNG/H₂)", u: "%", mn: 0, mx: 100, s: 5 },
    ballastTreatment: { l: "Ballast treatment", u: "%", mn: 0, mx: 100, s: 5 },
    cruiseShipCalls: { l: "Cruise ship calls", u: "/yr", mn: 0, mx: 300, s: 10 },
    cruiseShipRegulation: { l: "Cruise ship regulation", u: "%", mn: 0, mx: 100, s: 5, sourceHint: "0=current, 50=shore power required, 100=zero emission at berth. Affects port air quality and ballast discharge." },
    whaleWatchIntensity: { l: "Whale watching", u: "%", mn: 0, mx: 100, s: 5 },
    seattleThroughput: { l: "Seattle throughput", u: "%", mn: 20, mx: 200, s: 5 },
    tacomaThroughput: { l: "Tacoma throughput", u: "%", mn: 20, mx: 200, s: 5 },
    vancouverThroughput: { l: "Vancouver throughput", u: "%", mn: 20, mx: 200, s: 5 },
    bellinghamGrowthRate: { l: "Bellingham growth", u: "%", mn: 0, mx: 100, s: 5 },
    bremertonNavalActivity: { l: "Bremerton naval", u: "%", mn: 0, mx: 100, s: 5 },
    seattleCruiseCalls: { l: "Seattle cruise calls", u: "/yr", mn: 0, mx: 500, s: 10 },
    vancouverCruiseCalls: { l: "Vancouver cruise calls", u: "/yr", mn: 0, mx: 600, s: 10 },
    victoriaCruiseCalls: { l: "Victoria cruise calls", u: "/yr", mn: 0, mx: 500, s: 10 },
    seattleShorepower: { l: "Seattle shore power", u: "%", mn: 0, mx: 100, s: 5 },
    tacomaShorepower: { l: "Tacoma shore power", u: "%", mn: 0, mx: 100, s: 5 },
    vancouverShorepower: { l: "Vancouver shore power", u: "%", mn: 0, mx: 100, s: 5 },
    seattleVesselSpeed: { l: "Seattle speed zone", u: "%", mn: 0, mx: 100, s: 5 },
    tacomaVesselSpeed: { l: "Tacoma speed zone", u: "%", mn: 0, mx: 100, s: 5 },
    vancouverVesselSpeed: { l: "Vancouver speed zone", u: "%", mn: 0, mx: 100, s: 5 },
    environmentalLevyRate: { l: "Environmental levy", u: "%", mn: 0, mx: 10, s: 0.5 },
  }},
  ecosystem: { label: "Ecosystem & fisheries", ac: "#1D9E75", bg: "#E1F5EE", tip: "Biodiversity, salmon cohorts, orca population, kelp health, and fishing pressure", p: {
    baselineBiodiversity: { l: "Biodiversity", u: "%", mn: 20, mx: 100, s: 1 },
    fishingPressure: { l: "Fishing pressure", u: "%", mn: 0, mx: 100, s: 1 },
    protectedAreaFraction: { l: "Protected areas", u: "%", mn: 0, mx: 50, s: 1 },
    orcaProtectionLevel: { l: "Orca protection", u: "%", mn: 0, mx: 100, s: 5 },
    hatcheryFraction: { l: "Hatchery fraction", u: "%", mn: 0, mx: 80, s: 5 },
    greenCrabRemoval: { l: "Green crab removal", u: "%", mn: 0, mx: 100, s: 5 },
    compensatoryMortality: { l: "Compensatory mortality", u: "%", mn: 0, mx: 100, s: 5 },
    coManagementIndex: { l: "Tribal co-management", u: "%", mn: 0, mx: 100, s: 5 },
    eelgrassRestoration: { l: "Eelgrass restoration", u: "%", mn: 0, mx: 100, s: 5 },
    fishPassageInvestment: { l: "Fish passage", u: "%", mn: 0, mx: 100, s: 5 },
    aquacultureIntensity: { l: "Aquaculture intensity", u: "%", mn: 0, mx: 100, s: 5 },
    aquaculturePolicy: { l: "Closed containment", u: "%", mn: 0, mx: 100, s: 10, sourceHint: "DFO 2022 Open-Net Pen Transition Plan, Cohen Commission 2012. 0=open pens, 100=fully closed." },
    slrAdaptation: { l: "SLR strategy", u: "", mn: 0, mx: 2, s: 1, f: function(v) { return ["Hard armoring", "Status quo", "Living shorelines"][v] || "Status quo"; } },
    pinnipedCulling: { l: "Pinniped management", u: "%", mn: 0, mx: 100, s: 5, sourceHint: "Proposed MMPA amendments (HR 6749). 0=no culling, 100=aggressive removal. Reduces seal predation on salmon but also removes Bigg's orca prey base." },
  }},
  urban: { label: "Urban infrastructure", ac: "#534AB7", bg: "#EEEDFE", tip: "Population, wastewater, stormwater, energy, and US-Canada cross-border coordination", p: {
    population: { l: "Population", u: "M", mn: 3e6, mx: 15e6, s: 2e5, f: v => (v / 1e6).toFixed(1) },
    urbanizationRate: { l: "Urbanization", u: "%", mn: 10, mx: 80, s: 1 },
    wastewaterEfficiency: { l: "Wastewater", u: "%", mn: 20, mx: 99, s: 1 },
    energyCleanFraction: { l: "Clean energy", u: "%", mn: 0, mx: 100, s: 1 },
    stormwaterInfraAge: { l: "Infra age", u: "%", mn: 0, mx: 100, s: 5 },
    crossBorderCoord: { l: "US-Canada coord.", u: "%", mn: 0, mx: 100, s: 5 },
    greenInfraFraction: { l: "Green infrastructure", u: "%", mn: 0, mx: 50, s: 1 },
    urbanDensity: { l: "Urban density", u: "%", mn: 10, mx: 90, s: 5 },
    dataCenterGrowth: { l: "Data center growth", u: "%/yr", mn: 0, mx: 30, s: 1 },
    gridInvestment: { l: "Grid modernization", u: "%", mn: 0, mx: 100, s: 5 },
    smrPathway: { l: "SMR pathway", u: "", mn: 0, mx: 3, s: 1, f: function(v) { return ["None", "Standard (2032)", "Delayed (2035)", "Accelerated (2030)"][v] || "Standard (2032)"; } },
    fusionPathway: { l: "Fusion pathway", u: "", mn: 0, mx: 3, s: 1, f: function(v) { return ["None", "Late (2050)", "Mid (2042)", "Breakthrough (2035)"][v] || "None"; } },
    insuranceBaseRate: { l: "Insurance market regulation", u: "%", mn: 0, mx: 100, s: 5, sourceHint: "FEMA NFIP, Insurance Institute — higher = less regulated = faster repricing of climate risk" },
    stormwaterTreatment: { l: "Stormwater treatment", u: "%", mn: 0, mx: 100, s: 5, sourceHint: "PSP 2022 Action Agenda — bioretention, rain gardens, permeable pavement. Reduces 6PPD-q, Cu, PAH, microplastic delivery." },
    microplasticReduction: { l: "Microplastic reduction", u: "%", mn: 0, mx: 100, s: 5, sourceHint: "Laundry filters, stormwater filtration, tire reformulation (WA SB 5931)" },
    wastewaterInvestment: { l: "Wastewater capacity", u: "%", mn: 0, mx: 100, s: 5, sourceHint: "King County WTD, Metro Vancouver — plant upgrades, CSO separation, capacity expansion" },
    populationGrowthRate: { l: "Population growth", u: "%/yr", mn: 0, mx: 3, s: 0.1, sourceHint: "PSRC 2024 projections. Seattle metro ~1.2%/yr. Drives stormwater, wastewater, energy, VMT." },
    lightPollutionReduction: { l: "Light pollution reduction", u: "%", mn: 0, mx: 100, s: 5, sourceHint: "Rich & Longcore 2006. Dark sky ordinances, shielded fixtures. Reduces seabird/smolt mortality." },
    pharmReduction: { l: "Pharmaceutical reduction", u: "%", mn: 0, mx: 100, s: 5, sourceHint: "Meador et al. 2016 (NOAA). Advanced wastewater treatment removes fluoxetine, estradiol, antibiotics." },
  }},
  infrastructure: { label: "Infrastructure", ac: "#546E7A", bg: "#ECEFF1", tip: "Transportation corridors (I-5, BNSF, ferries, BC Hwy 1), pipelines, levees, utilities — vulnerability to landslides, earthquakes, flooding, and climate", p: {
    i5MaintenanceInvestment: { l: "I-5 maintenance", u: "%", mn: 0, mx: 100, s: 5 },
    railSafetyInvestment: { l: "Rail safety", u: "%", mn: 0, mx: 100, s: 5 },
    ferryInvestment: { l: "Ferry investment", u: "%", mn: 0, mx: 100, s: 5 },
    bcHighwayResilience: { l: "BC highway resilience", u: "%", mn: 0, mx: 100, s: 5 },
    pipelineSafetyInvestment: { l: "Pipeline safety", u: "%", mn: 0, mx: 100, s: 5 },
    leveeInvestment: { l: "Levee investment", u: "%", mn: 0, mx: 100, s: 5 },
    gridHardeningInvestment: { l: "Grid hardening", u: "%", mn: 0, mx: 100, s: 5 },
    waterInfraInvestment: { l: "Water infrastructure", u: "%", mn: 0, mx: 100, s: 5 },
    infrastructureRedundancy: { l: "Redundancy invest.", u: "%", mn: 0, mx: 100, s: 5 },
  }},
  publicHealth: { label: "Public health", ac: "#C62828", bg: "#FFEBEE", tip: "Shellfish closures, smoke health burden, drinking water safety, Vibrio risk, fish consumption advisories, environmental health disparities", p: {
    habMonitoringIntensity: { l: "HAB monitoring", u: "%", mn: 0, mx: 100, s: 5 },
    drinkingWaterInvestment: { l: "Water treatment", u: "%", mn: 0, mx: 100, s: 5 },
    smokePreparedness: { l: "Smoke preparedness", u: "%", mn: 0, mx: 100, s: 5 },
    sewerSeparation: { l: "Sewer separation", u: "%", mn: 0, mx: 100, s: 5 },
    fishAdvisoryCompliance: { l: "Advisory compliance", u: "%", mn: 0, mx: 100, s: 5 },
  }},
  tribal: { label: "Tribal governance", ac: "#8B6914", bg: "#F5EFE0", tip: "Treaty rights, co-management, Traditional Ecological Knowledge, cultural health, environmental justice — legally binding governance, not advisory. Treaty rights themselves are constitutionally protected and not adjustable; these sliders control funding and institutional capacity for implementation.", p: {
    treatyImplementation: { l: "Treaty implementation funding", u: "%", mn: 0, mx: 100, s: 5 },
    tribalManagementFunding: { l: "Co-management funding", u: "%", mn: 0, mx: 100, s: 5 },
    tekIntegration: { l: "TEK integration", u: "%", mn: 0, mx: 100, s: 5 },
    tribalRestorationInvestment: { l: "Tribal restoration", u: "%", mn: 0, mx: 100, s: 5 },
    culturalSiteProtection: { l: "Cultural site protection", u: "%", mn: 0, mx: 100, s: 5 },
  }},
  fisheries: { label: "Fisheries management", ac: "#1565C0", bg: "#E3F2FD", tip: "Adaptive salmon harvest: stock assessment, weak stock management, SRKW prey protection, treaty allocation, recreational/commercial sectors", p: {
    stockAssessmentFunding: { l: "Assessment funding", u: "%", mn: 0, mx: 100, s: 5 },
    harvestRuleStrictness: { l: "Harvest strictness", u: "%", mn: 0, mx: 100, s: 5 },
    orcaPreyProtectionLevel: { l: "Orca prey protection", u: "%", mn: 0, mx: 100, s: 5 },
    // Boldt Decision (United States v. Washington, 1974) guarantees 50% minimum treaty allocation.
    // This is settled federal law affirmed by the Supreme Court (1979), not a policy variable.
    // Values above 50% represent enhanced conservation priority or expanded treaty implementation.
    tribalHarvestAllocation: { l: "Treaty harvest allocation", u: "%", mn: 50, mx: 60, s: 1 },
    recreationalFishingEffort: { l: "Recreational effort", u: "%", mn: 0, mx: 100, s: 5 },
    markSelectiveFishing: { l: "Mark-selective fishing", u: "%", mn: 0, mx: 100, s: 5 },
    pacificSalmonTreaty: { l: "PST compliance", u: "%", mn: 0, mx: 100, s: 5, sourceHint: "Pacific Salmon Treaty (1985, renewed 2019). At 100%: US share of Fraser stocks ~18%. Low compliance → overharvest of shared stocks." },
  }},
  nearshore: { label: "Nearshore habitat", ac: "#C2956B", bg: "#F5EDE3", tip: "Estuaries, salt marsh, eelgrass beds, kelp canopy, forage fish beaches, pocket estuaries, shoreline armoring, and contaminant hotspots", p: {
    armorRemovalRate: { l: "Armor removal", u: "‰/yr", mn: 0, mx: 1000, s: 50 },
    pocketEstuaryRestoration: { l: "Pocket estuary restore", u: "%", mn: 0, mx: 100, s: 5 },
    marshRestorationRate: { l: "Marsh restoration", u: "‰/yr", mn: 0, mx: 500, s: 25 },
    superfundRemediationRate: { l: "Superfund cleanup", u: "%", mn: 0, mx: 100, s: 5 },
    nearshoreInvestment: { l: "Nearshore invest.", u: "%", mn: 0, mx: 100, s: 5 },
    benthicProtection: { l: "Benthic habitat protection", u: "%", mn: 0, mx: 100, s: 5, sourceHint: "Greene & Barrie 2011 — protection of rocky reef and sand wave habitats from dredging, anchoring, cable laying" },
    dredgingRestriction: { l: "Dredging restriction", u: "%", mn: 0, mx: 100, s: 5, sourceHint: "Reduces sand wave destruction and benthic disturbance from maintenance dredging" },
  }},
  psWatersheds: { label: "PS Watersheds", ac: "#2E7D32", bg: "#E8F5E9", tip: "6 Puget Sound river systems: Skagit, Snohomish, Nooksack, Puyallup, Nisqually, Stillaguamish — salmon habitat and water quality", p: {
    skagitDamPolicy: { l: "Skagit dam policy", u: "%", mn: 0, mx: 100, s: 5 },
    nisquallyRestorationLevel: { l: "Nisqually restoration", u: "%", mn: 0, mx: 100, s: 5 },
    nooksackDairyIntensity: { l: "Nooksack dairy", u: "%", mn: 0, mx: 100, s: 5 },
    puyallupUrbanGrowth: { l: "Puyallup urban growth", u: "%", mn: 0, mx: 100, s: 5 },
    stillaguamishForestry: { l: "Stillaguamish forestry", u: "%", mn: 0, mx: 100, s: 5 },
    psHabitatInvestment: { l: "PS habitat invest.", u: "%", mn: 0, mx: 100, s: 5 },
  }},
  biogeochem: { label: "Biogeochemistry", ac: "#5B4A8C", bg: "#EDEAF5", tip: "Nutrient cycling, carbonate chemistry, dissolved oxygen budgets — the chemistry that controls water quality and species habitat", p: {
    denitrificationRate: { l: "Denitrification", u: "%", mn: 0, mx: 40, s: 1 },
    sedimentOxygenDemand: { l: "SOD modifier", u: "%", mn: 0, mx: 200, s: 5 },
    calcificationRate: { l: "Calcification rate", u: "%", mn: 0, mx: 200, s: 5 },
    atmosphericCO2: { l: "Atmospheric CO₂", u: "ppm", mn: 280, mx: 1000, s: 10 },
    sedimentBurialRate: { l: "Sediment burial", u: "‰/yr", mn: 0, mx: 50, s: 5 },
  }},
  pacific: { label: "Pacific Ocean", ac: "#1B4F72", bg: "#E3EBF2", tip: "Pacific boundary forcing: California Current upwelling, source water properties, marine heat waves, salmon marine survival", p: {
    upwellingModifier: { l: "Upwelling modifier", u: "%", mn: 50, mx: 150, s: 5 },
    pacificO2DeclineRate: { l: "Pacific O₂ decline", u: "%", mn: 0, mx: 20, s: 1 },
    pacificDICIncrease: { l: "Ocean acidification", u: "%", mn: 0, mx: 300, s: 10 },
    alaskaHatcheryCompetition: { l: "Alaska hatchery comp.", u: "%", mn: 0, mx: 100, s: 5 },
    mhwProbabilityMod: { l: "MHW probability", u: "%", mn: 0, mx: 300, s: 10 },
  }},
  climate: { label: "Climate & atmosphere", ac: "#4A6FA5", bg: "#E8EDF5", tip: "Regional atmospheric dynamics: ENSO/PDO oscillations, atmospheric rivers, rain shadow, smoke transport", p: {
    arIntensityMod: { l: "AR intensity mod", u: "%", mn: 0, mx: 200, s: 10 },
    pdoPhaseOverride: { l: "PDO phase override", u: "", mn: 0, mx: 3, s: 1, f: function(v) { return ["Auto", "Force warm", "Force cool", "Force neutral"][v] || "Auto"; } },
    smokeTransportEfficiency: { l: "Smoke transport", u: "%", mn: 0, mx: 100, s: 5 },
    fogDeclineRate: { l: "Fog decline rate", u: "%/decade", mn: 0, mx: 10, s: 0.5 },
  }},
  fraser: { label: "Fraser River Basin", ac: "#2D6A4F", bg: "#E3F0E8", tip: "Fraser River: 233,000 km² basin, dominant freshwater input to Georgia Strait. Controls snowpack, glaciers, salmon stocks, and water quality", p: {
    nechakoDiversionFrac: { l: "Nechako restoration", u: "%", mn: 0, mx: 100, s: 5 },
    pineBeetleSeverity: { l: "Pine beetle severity", u: "%", mn: 0, mx: 100, s: 5 },
    fireSuppressionEffort: { l: "Fire suppression", u: "%", mn: 0, mx: 100, s: 5 },
    miningIntensity: { l: "Mining intensity", u: "%", mn: 0, mx: 100, s: 5 },
    forestryIntensity: { l: "Forestry intensity", u: "%", mn: 0, mx: 100, s: 5 },
    fraserAgIntensity: { l: "Agriculture intensity", u: "%", mn: 0, mx: 100, s: 5 },
    fraserUrbanization: { l: "Lower Mainland urban.", u: "%", mn: 0, mx: 100, s: 5 },
    bigBarPassage: { l: "Big Bar passage", u: "%", mn: 0, mx: 100, s: 5 },
    fraserHabitatRestoration: { l: "Habitat restoration", u: "%", mn: 0, mx: 100, s: 5 },
    fraserFishingPressure: { l: "Fraser fishing", u: "%", mn: 0, mx: 100, s: 5 },
    sockeyeHatchery: { l: "Sockeye hatchery", u: "%", mn: 0, mx: 100, s: 5 },
    chinookHatchery: { l: "Chinook hatchery", u: "%", mn: 0, mx: 100, s: 5 },
  }},
};

// High-leverage parameters: data-driven importance from RF-based global
// sensitivity analysis (see scripts/sensitivity_analysis.mjs).
// Falls back to manual descriptions where the computed data doesn't have
// a human-readable explanation.
//
// The HIGH_LEVERAGE_COMPUTED map from sensitivitySummary.js provides the
// numerical importance scores. This map provides the human-readable WHY.
const HIGH_LEVERAGE = {
  fishingPressure: "Salmon run strength → orca prey → orca demographics",
  fishPassageInvestment: "Salmon cohort survival + hydro generation tradeoff",
  wastewaterEfficiency: "Nutrient loading → DO (esp. Hood Canal) + HAB risk",
  sspPathway: "Global warming trajectory → SST, snowpack, phenology, all species",
  containerThroughput: "Vessel traffic → underwater noise → orca, porpoise foraging",
  orcaProtectionLevel: "Vessel noise + strike risk → all 3 SRKW pods",
  greenCrabRemoval: "Eelgrass health → herring spawning → salmon → orca cascade",
  eelgrassRestoration: "Herring spawning habitat → forage fish → salmon → orca",
  protectedAreaFraction: "MPAs → rockfish recovery → food web integrity",
  bigBarPassage: "Fraser Chinook/sockeye passage → SRKW prey base → orca demographics",
  fraserFishingPressure: "Fraser salmon harvest → spawner escapement → orca prey availability",
  treatyImplementation: "Treaty governance → co-management → restoration effectiveness",
  tribalManagementFunding: "Co-management capacity → harvest rules → salmon recovery",
  i5MaintenanceInvestment: "I-5 corridor reliability → trade access → economic resilience",
  gridInvestment: "Grid modernization → reliability → demand management",
  dataCenterGrowth: "Demand growth → grid stress → generation mix shift",
  habMonitoringIntensity: "HAB detection → closure timing → public health protection",
  pacificO2DeclineRate: "Pacific source water deoxygenation → basin DO → species stress",
  slrScenario: "Coastal squeeze, forage fish beach habitat, displacement",
  energyCleanFraction: "Grid emissions → atmospheric CO₂ → ocean acidification trajectory",
  nechakoDiversionFrac: "Nechako flow restoration → Fraser cooling → sockeye en-route survival",
  damRemovalPolicy: "Sediment supply + fish passage + flow regime for 3 river systems",
};

export { PM, HIGH_LEVERAGE };
