import type { Jurisdiction } from './region.js';

export type SourcePlane =
  | 'solidEarth'
  | 'weatherHydromet'
  | 'oceanOffshore'
  | 'humanPulse'
  | 'ecologyEconomy';

export type DeliveryMode = 'push' | 'poll';

export interface SourceSpec {
  id: string;
  name: string;
  endpoint: string;
  cadenceSec: number;
  delivery: DeliveryMode;
  auth: 'none' | 'apiKey' | 'oauth' | 'token';
  license: string;
  jurisdiction: Jurisdiction | 'multi';
  plane: SourcePlane;
  isPrediction: boolean;
  sovereign?: boolean;
  sensitive?: boolean;
  notes?: string;
}

// The registry. Every fetcher MUST clip to PNW (see region.ts).
// Solid-earth and ocean sources carry isPrediction: false. Only forecast-model
// sources may set isPrediction: true, and only the Forecast contract may carry them.
export const SOURCES: readonly SourceSpec[] = [
  // ----- Solid earth -----
  {
    id: 'earthscope.fdsn.dataselect',
    name: 'EarthScope FDSN dataselect',
    endpoint: 'https://service.iris.edu/fdsnws/dataselect/1/',
    cadenceSec: 60,
    delivery: 'poll',
    auth: 'token',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'solidEarth',
    isPrediction: false,
  },
  {
    id: 'earthscope.fdsn.station',
    name: 'EarthScope FDSN station',
    endpoint: 'https://service.iris.edu/fdsnws/station/1/',
    cadenceSec: 86400,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'solidEarth',
    isPrediction: false,
  },
  {
    id: 'earthscope.seedlink',
    name: 'EarthScope SeedLink real-time',
    endpoint: 'rtserve.iris.washington.edu:18000',
    cadenceSec: 1,
    delivery: 'push',
    auth: 'token',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'solidEarth',
    isPrediction: false,
  },
  {
    id: 'earthscope.nota.gnss',
    name: 'EarthScope Network of the Americas GNSS',
    endpoint: 'https://data.unavco.org/archive/gnss/',
    cadenceSec: 86400,
    delivery: 'poll',
    auth: 'token',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'solidEarth',
    isPrediction: false,
  },
  {
    id: 'pnsn.tremor',
    name: 'PNSN tremor catalog',
    endpoint: 'https://pnsn.org/tremor',
    cadenceSec: 600,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'solidEarth',
    isPrediction: false,
  },
  {
    id: 'usgs.fdsn.events',
    name: 'USGS FDSN earthquake catalog',
    endpoint: 'https://earthquake.usgs.gov/fdsnws/event/1/',
    cadenceSec: 60,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'solidEarth',
    isPrediction: false,
  },
  {
    id: 'usgs.volcano',
    name: 'USGS Volcano API',
    endpoint: 'https://volcanoes.usgs.gov/hans-public/api/volcano/',
    cadenceSec: 600,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'solidEarth',
    isPrediction: false,
  },
  {
    id: 'shakealert',
    name: 'ShakeAlert (mirror, never originate)',
    endpoint: 'https://earthquake.usgs.gov/data/shakealert/',
    cadenceSec: 1,
    delivery: 'push',
    auth: 'token',
    license: 'restricted',
    jurisdiction: 'multi',
    plane: 'solidEarth',
    isPrediction: false,
    notes: 'Official warning system. We mirror with officialSource set, never originate.',
  },
  {
    id: 'ntwc.tsunami',
    name: 'National Tsunami Warning Center',
    endpoint: 'https://www.tsunami.gov/',
    cadenceSec: 60,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'solidEarth',
    isPrediction: false,
  },

  // ----- Weather and hydromet -----
  {
    id: 'nws.observations',
    name: 'NWS station observations',
    endpoint: 'https://api.weather.gov/stations',
    cadenceSec: 300,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'weatherHydromet',
    isPrediction: false,
  },
  {
    id: 'nws.alerts',
    name: 'NWS alerts API',
    endpoint: 'https://api.weather.gov/alerts/active',
    cadenceSec: 60,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'weatherHydromet',
    isPrediction: false,
    notes: 'Mirrored into HazardEvent with officialSource set.',
  },
  {
    id: 'noaa.hrrr',
    name: 'NOAA HRRR numerical forecast',
    endpoint: 'https://noaa-hrrr-bdp-pds.s3.amazonaws.com/',
    cadenceSec: 3600,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'weatherHydromet',
    isPrediction: true,
  },
  {
    id: 'noaa.gfs',
    name: 'NOAA GFS numerical forecast',
    endpoint: 'https://noaa-gfs-bdp-pds.s3.amazonaws.com/',
    cadenceSec: 21600,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'weatherHydromet',
    isPrediction: true,
  },
  {
    id: 'nexrad',
    name: 'NEXRAD radar',
    endpoint: 'https://noaa-nexrad-level2.s3.amazonaws.com/',
    cadenceSec: 300,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'weatherHydromet',
    isPrediction: false,
  },
  {
    id: 'ww3',
    name: 'WaveWatch III',
    endpoint: 'https://nomads.ncep.noaa.gov/pub/data/nccf/com/wave/',
    cadenceSec: 21600,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'weatherHydromet',
    isPrediction: true,
  },
  {
    id: 'noaa.tides',
    name: 'NOAA Tides and Currents',
    endpoint: 'https://api.tidesandcurrents.noaa.gov/api/prod/',
    cadenceSec: 360,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'weatherHydromet',
    isPrediction: false,
  },
  {
    id: 'usgs.nwis',
    name: 'USGS NWIS streamflow',
    endpoint: 'https://waterservices.usgs.gov/nwis/iv/',
    cadenceSec: 900,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'weatherHydromet',
    isPrediction: false,
  },
  {
    id: 'eccc.hydrometric',
    name: 'Environment Canada hydrometric',
    endpoint: 'https://api.weather.gc.ca/collections/hydrometric-realtime/',
    cadenceSec: 900,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'CA-BC',
    plane: 'weatherHydromet',
    isPrediction: false,
  },
  {
    id: 'snotel',
    name: 'USDA SNOTEL snow',
    endpoint: 'https://wcc.sc.egov.usda.gov/awdbWebService/services',
    cadenceSec: 3600,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'weatherHydromet',
    isPrediction: false,
  },
  {
    id: 'swpc',
    name: 'NOAA Space Weather Prediction Center',
    endpoint: 'https://services.swpc.noaa.gov/',
    cadenceSec: 300,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'weatherHydromet',
    isPrediction: false,
  },

  // ----- Human pulse (WorldView) -----
  {
    id: 'opensky',
    name: 'OpenSky aircraft',
    endpoint: 'https://opensky-network.org/api',
    cadenceSec: 10,
    delivery: 'poll',
    auth: 'apiKey',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'humanPulse',
    isPrediction: false,
  },
  {
    id: 'airplanes.live',
    name: 'airplanes.live aircraft (unfiltered)',
    endpoint: 'https://api.airplanes.live/v2/',
    cadenceSec: 5,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'humanPulse',
    isPrediction: false,
  },
  {
    id: 'celestrak',
    name: 'CelesTrak TLE',
    endpoint: 'https://celestrak.org/NORAD/elements/',
    cadenceSec: 21600,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'humanPulse',
    isPrediction: false,
  },
  {
    id: 'aisstream',
    name: 'AISStream vessel traffic',
    endpoint: 'wss://stream.aisstream.io/v0/stream',
    cadenceSec: 1,
    delivery: 'push',
    auth: 'apiKey',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'humanPulse',
    isPrediction: false,
  },
  {
    id: 'osm.overpass',
    name: 'OpenStreetMap via Overpass',
    endpoint: 'https://overpass-api.de/api/interpreter',
    cadenceSec: 86400,
    delivery: 'poll',
    auth: 'none',
    license: 'ODbL',
    jurisdiction: 'multi',
    plane: 'humanPulse',
    isPrediction: false,
  },
  {
    id: 'wsdot.cameras',
    name: 'WSDOT traveler cameras',
    endpoint: 'https://wsdot.wa.gov/traffic/api/',
    cadenceSec: 60,
    delivery: 'poll',
    auth: 'apiKey',
    license: 'open',
    jurisdiction: 'US-WA',
    plane: 'humanPulse',
    isPrediction: false,
  },
  {
    id: 'tripcheck',
    name: 'Oregon TripCheck cameras',
    endpoint: 'https://www.tripcheck.com/',
    cadenceSec: 60,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'US-OR',
    plane: 'humanPulse',
    isPrediction: false,
  },
  {
    id: 'drivebc',
    name: 'Drive BC cameras',
    endpoint: 'https://www.drivebc.ca/',
    cadenceSec: 60,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'CA-BC',
    plane: 'humanPulse',
    isPrediction: false,
  },

  // ----- Ocean and offshore -----
  {
    id: 'dart.ndbc',
    name: 'DART tsunami buoys (NDBC)',
    endpoint: 'https://www.ndbc.noaa.gov/dart.shtml',
    cadenceSec: 900,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'oceanOffshore',
    isPrediction: false,
  },
  {
    id: 'onc.erddap',
    name: 'Ocean Networks Canada ERDDAP',
    endpoint: 'https://data.oceannetworks.ca/erddap/',
    cadenceSec: 600,
    delivery: 'poll',
    auth: 'token',
    license: 'open',
    jurisdiction: 'CA-BC',
    plane: 'oceanOffshore',
    isPrediction: false,
  },
  {
    id: 'ooi.erddap',
    name: 'OOI ERDDAP (Cabled Array, Oregon shelf)',
    endpoint: 'https://erddap.dataexplorer.oceanobservatories.org/erddap/',
    cadenceSec: 600,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'US-OR',
    plane: 'oceanOffshore',
    isPrediction: false,
  },
  {
    id: 'nanoos.erddap',
    name: 'NANOOS ERDDAP',
    endpoint: 'https://nvs.nanoos.org/erddap/',
    cadenceSec: 900,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'oceanOffshore',
    isPrediction: false,
  },
  {
    id: 'podaac.sst',
    name: 'PODAAC satellite SST and altimetry',
    endpoint: 'https://podaac.jpl.nasa.gov/',
    cadenceSec: 86400,
    delivery: 'poll',
    auth: 'token',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'oceanOffshore',
    isPrediction: false,
  },
  {
    id: 'crw',
    name: 'NOAA Coral Reef Watch',
    endpoint: 'https://coralreefwatch.noaa.gov/',
    cadenceSec: 86400,
    delivery: 'poll',
    auth: 'none',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'oceanOffshore',
    isPrediction: false,
  },
  {
    id: 'copernicus.marine',
    name: 'Copernicus Marine',
    endpoint: 'https://data.marine.copernicus.eu/',
    cadenceSec: 86400,
    delivery: 'poll',
    auth: 'apiKey',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'oceanOffshore',
    isPrediction: false,
  },
  {
    id: 'gfw.fourwings',
    name: 'Global Fishing Watch 4Wings (fishing effort)',
    endpoint: 'https://gateway.api.globalfishingwatch.org/v3/',
    cadenceSec: 86400,
    delivery: 'poll',
    auth: 'token',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'oceanOffshore',
    isPrediction: false,
  },
  {
    id: 'gfw.sar',
    name: 'Global Fishing Watch SAR detections',
    endpoint: 'https://gateway.api.globalfishingwatch.org/v3/',
    cadenceSec: 86400,
    delivery: 'poll',
    auth: 'token',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'oceanOffshore',
    isPrediction: false,
  },
  {
    id: 'gfw.events',
    name: 'Global Fishing Watch Events (encounters, loitering, AIS-off)',
    endpoint: 'https://gateway.api.globalfishingwatch.org/v3/',
    cadenceSec: 86400,
    delivery: 'poll',
    auth: 'token',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'oceanOffshore',
    isPrediction: false,
  },

  // ----- Ecology and economy -----
  {
    id: 'acartia',
    name: 'Acartia and The Whale Museum sightings',
    endpoint: 'https://acartia.io/',
    cadenceSec: 600,
    delivery: 'poll',
    auth: 'apiKey',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'ecologyEconomy',
    isPrediction: false,
    sensitive: true,
    notes: 'Resident orca positions deliberately fuzzed.',
  },
  {
    id: 'fred',
    name: 'FRED economic series',
    endpoint: 'https://api.stlouisfed.org/fred/',
    cadenceSec: 86400,
    delivery: 'poll',
    auth: 'apiKey',
    license: 'open',
    jurisdiction: 'multi',
    plane: 'ecologyEconomy',
    isPrediction: false,
  },
];

export function sourcesByPlane(plane: SourcePlane): SourceSpec[] {
  return SOURCES.filter((s) => s.plane === plane);
}

export function getSource(id: string): SourceSpec | undefined {
  return SOURCES.find((s) => s.id === id);
}
